export const AUTH_FORM_CHANGE = "AUTH_FORM_CHANGE";
export const SET_AUTH_LOADING = "SET_AUTH_LOADING";
export const SET_AUTH_FORM_ERROR = "SET_AUTH_FORM_ERROR";
export const SET_AUTH_ERROR = "SET_AUTH_ERROR";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const SET_USER_AUTHENTICATED = "SET_USER_AUTHENTICATED";
export const LOGOUT_USER = "LOGOUT_USER";