export const OPEN_POST_MODAL = "OPEN_POST_MODAL";
export const CLOSE_POST_MODAL = "CLOSE_POST_MODAL";
export const POST_MODAL_FORM_CHANGE = "POST_MODAL_FORM_CHANGE";
export const SET_MODAL_FORM_ERROR = "SET_MODAL_FORM_ERROR";
export const SET_MODAL_REQUEST_ERROR = "SET_MODAL_REQUEST_ERROR";